Repository chaintex/TomoSwap, pull requests merged in 2019-03, with the labels that each got.

#32 Locked web3 version
  .travis.yml
  package.json
  src/sagas/transactionSaga.js
  src/services/web3Service.js
Labels: bug

#30 Add validation balance before opening confirm modal
  src/components/swap/Swap.js
  src/components/transfer/Transfer.js
  src/config/tokens.js
Labels: bug

#31 Immediately update default gas used when src/dest token changed
  src/components/swap/Swap.js
  src/components/transfer/Transfer.js
  src/sagas/swapSaga.js
  src/sagas/transactionSaga.js
  src/sagas/transferSaga.js
Labels: bug

#38 Update calculate src amount when selecting percentage
  src/components/commons/InputGroup.js
  src/components/swap/SwapView.js
  src/components/transfer/TransferView.js
Labels: bug

#40 Wrong text for percentage balance in transfer view
  src/components/commons/InputGroup.js
Labels: bug

#29 Add more links to home page
  src/components/layouts/Footer.js
  src/components/layouts/Header.js
Labels: WIP

#39 add section our team and advisor
  src/assets/images/aboutus/loi_luu.png
  src/assets/images/aboutus/long_vuong.jpg
  src/assets/images/aboutus/mark_nguyen.jpg
  src/assets/images/aboutus/mike_le.png
  src/assets/images/aboutus/tu_nguyen.jpg
  src/assets/images/aboutus/victor_tran.png
  src/assets/scss/components/aboutus.scss
  src/assets/scss/components/market.scss
  src/assets/scss/elements.scss
  src/assets/scss/index.scss
  src/components/layouts/AboutUs.js
  src/components/layouts/Body.js
  src/components/layouts/Footer.js
  src/components/layouts/Header.js
Labels: newfeature

#46 Reset source amount when source token did change
  src/sagas/swapSaga.js
  src/sagas/transferSaga.js
Labels: bug

#48 Fix failed to call network because big number is not integer
  src/services/networkService.js
  src/utils/helpers.js
Labels: bug

#49 Format address to display in transaction view
  src/components/transaction/TransactionView.js
Labels: bug

#45 Reset token balances when removed account, check balance not loaded with undefine value
  src/components/commons/InputGroup.js
  src/components/swap/Swap.js
  src/components/transfer/Transfer.js
  src/sagas/accountSaga.js
Labels: bug

#53 Add enter password to approve transaction for keystore, add confirm status to approve modal
  src/components/swap/Swap.js
  src/components/swap/SwapView.js
  src/sagas/swapSaga.js
  src/services/networkService.js
Labels: bug

#55 Reset balance when wallet changed
  src/components/account/ImportAccount.js
  src/components/commons/InputGroup.js
  src/config/env.js
  src/sagas/accountSaga.js
Labels: bug

#58 Fix error message for exchange rate to be more consistent
  src/sagas/swapSaga.js
Labels: improve

#61 Reset source amount, to address after sent transaction
  src/components/transaction/Transaction.js
Labels: improve

#62 Fix too many decimals when selected percentage balance
  src/components/commons/InputGroup.js
Labels: bug

#64 Fix not reset amount/address if select new swap/transfer
  src/components/transaction/Transaction.js
  src/components/transaction/TransactionView.js
Labels: bug

#60 Send approve transactions in background for keystore/private key wallet
  src/components/swap/Swap.js
  src/components/swap/SwapView.js
  src/sagas/swapSaga.js
  src/sagas/transactionSaga.js
Labels: improve

#68 Check transfer/swap transaction fee with TOMO balance
  src/components/swap/Swap.js
  src/components/transfer/Transfer.js
  src/sagas/swapSaga.js
  src/sagas/transferSaga.js
Labels: bug

#26 Add import using private key
  src/actions/accountAction.js
  src/components/account/ImportAccount.js
  src/components/account/ImportAccountView.js
  src/components/commons/PasswordInput.js
  src/components/commons/PrivateKeyInput.js
  src/config/app.js
  src/reducers/accountReducer.js
  src/services/accountServices/PrivateKeyService.js
Labels: newfeature

#69 Add vi and en translation texts
  src/assets/translations/en.json
  src/assets/translations/vi.json
Labels: newfeature

#76 Add try catch when calling contracts to prevent crash
  src/sagas/swapSaga.js
  src/sagas/transactionSaga.js
  src/services/networkService.js
Labels: bug
